service: aws-sqs-consumer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer

plugins:
  - serverless-lift
  - serverless-plugin-typescript

